name: GithubPages

on:
  push:
    branches:
      - master

jobs:
  build-wasm-and-push-pages:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      pages: write
      contents: write

    steps:
      - uses: olegtarasov/get-tag@v2.1.2
        id: get_version
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
        with:
          targets: wasm32-unknown-unknown
      - name: install wasm-bindgen-cli
        run: |
          cargo install wasm-bindgen-cli

      - name: Build
        run: |
          cargo build --release --target wasm32-unknown-unknown

      - name: Prepare package
        run: |
          wasm-bindgen --no-typescript --out-name bevy-minecraft-rs-wasm --out-dir wasm --target web target/wasm32-unknown-unknown/release/bevy-minecraft-rs.wasm
          cp -r assets wasm/
          cp index.html wasm/

      - name: Setup gh-pages
        uses: actions/configure-pages@v3

      - name: Upload assets to gh-pages
        uses: actions/upload-pages-artifact@v1.0.8
        with:
          path: wasm/
          retention-days: 1

      - name: Deploy to gh-pages
        uses: actions/deploy-pages@v2
